<?php
use Zend\Form\Element\Textarea;

echo $this->blockAttachmentsForm($block);
?>
<h4>Title</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title')); ?>" name="o:block[__blockIndex__][o:data][title]">
  </div>
</div>

<h4>Text</h4>
<?php
  $textarea = new Textarea("o:block[__blockIndex__][o:data][text]");
  $textarea->setAttribute('class', 'block-html full wysiwyg');
  if ($block) {
      $textarea->setAttribute('value', $block->dataValue('text'));
  }
?>
<?php echo $this->formRow($textarea);?>

<!-- <div class="field">
  <div class="field-meta">
      <label>Link</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('link')) ?>" name="o:block[__blockIndex__][o:data][link]">
  </div>
</div>
<div class="field">
  <div class="field-meta">
      <label>Link label</label>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('label')) ?>" name="o:block[__blockIndex__][o:data][label]">
  </div>
</div> -->
<?php if(isset($block)):
  $reverse = $block->dataValue('reverse');
else:
  $reverse = 0;
endif;?>
<div class="field">
  <div class="field-meta">
      <label>Reverse</label>
      <a href="#" class="expand" aria-label="Expand" title="Expand"></a>
      <div class="collapsible">
        <div class="field-description">Move text to the right and image to the left</div>
      </div>
  </div>
  <div class="inputs">
      <input type="checkbox" class="" value="reverse" <?php echo ($reverse == 'reverse' ? 'checked' : '') ?> name="o:block[__blockIndex__][o:data][reverse]">
  </div>
</div>
<!-- <?php if(isset($block)):
  $itemurl = $block->dataValue('itemurl');
else:
  $itemurl = '';
endif;?>
<div class="field">
  <div class="field-meta">
      <label>Add zoom?</label>
      <a href="#" class="expand" aria-label="Expand" title="Expand"></a>
      <div class="collapsible">
        <div class="field-description">Add a link to the original image that opens in a new tab/window</div>
      </div>
  </div>
  <div class="inputs">
      <input type="checkbox" class="" value="itemurl" <?php echo ($itemurl == 'itemurl' ? 'checked' : '') ?> name="o:block[__blockIndex__][o:data][itemurl]">
  </div>
</div> -->
<?php if(isset($block)):
  $small = $block->dataValue('small');
else:
  $small = 0;
endif;?>
<div class="field">
  <div class="field-meta">
      <label>Contain image</label>
      <a href="#" class="expand" aria-label="Expand" title="Expand"></a>
      <div class="collapsible">
        <div class="field-description">Image is set to be contained. Useful for screenshots to be shown in their entirety.</div>
      </div>
  </div>
  <div class="inputs">
      <input type="checkbox" class="" value="small" <?php echo ($small == 'small' ? 'checked' : '') ?> name="o:block[__blockIndex__][o:data][small]">
  </div>
</div>
<div class="field">
  <div class="field-meta">
      <label>Image ratio</label>
      <a href="#" class="expand" aria-label="Expand" title="Expand"></a>
      <div class="collapsible">
        <div class="field-description">Set the ratio of the image (ex. 16 / 9). Exact dimensions of the image can be used too (width / height). Default is 16/9.</div>
      </div>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '16/9' : $block->dataValue('ratio')) ?>" name="o:block[__blockIndex__][o:data][ratio]">
  </div>
</div>
<div class="field">
  <div class="field-meta">
      <label>Image size</label>
      <a href="#" class="expand" aria-label="Expand" title="Expand"></a>
      <div class="collapsible">
        <div class="field-description">Set relative size of image to text block. Either 1, 2 or 3 (or more). The bigger the number, the more the image will shrink. Default is 1.</div>
      </div>
  </div>
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '1' : $block->dataValue('shrink')) ?>" name="o:block[__blockIndex__][o:data][shrink]">
  </div>
</div>