<?php
$translate = $this->plugin('translate');
$searchValue = $this->escapeHtml($this->params()->fromQuery('fulltext_search', ''));
?>
  <form class="has-icons-right" action="http://localhost:9014/s/libis/index/search?site_id=4" id="search-form">
    <div class="field has-addons">
      <div class="control">
        <input class="input is-small" type="search" name="fulltext_search" value="<?php echo $searchValue; ?>"
            placeholder="<?php echo $translate('Search'); ?>"
            aria-label="<?php echo $translate('Search'); ?>">
      </div>
      <!-- <div class="control">
        <a class="button is-primary is-medium">
          <span class="icon is-small">
            <i class="fas fa-search"></i>
          </span>
        </a>
      </div> -->
    </div>
  </form> 
