<?php if(($block->dataValue('ratio'))):
$ratio = $block->dataValue('ratio');
else:
  $ratio = 16/9;
endif;
if(($block->dataValue('shrink'))):
  $shrink = $block->dataValue('shrink');
else:
  $shrink = 1;
endif;
if(($block->dataValue('small'))):
  $objectfit = 'contain';
else:
  $objectfit = 'cover';
endif;
$media = $attachments[0]->media();
$oUrl = $media->originalUrl();
?>
<style>
.openimage {
  cursor: zoom-in;
}
.figs {
  background-color: #222;
  color: #fff;
  padding: 3px 10px;
  text-align: center;
  position: relative;
  bottom: 1.19rem;
  opacity: 0.8;
  width: fit-content;
  border-top-right-radius: 20%;
  border-bottom-right-radius: 0%;
  font-size: 0.5rem;
}
</style>
<script>
  function OpenImage(url) {
  window.open(url,'_blank');
  }
</script>

<section>
  <div class="container">
    <div class="flex-image-figure" style="display: flex; flex-wrap: nowrap; width: 100%; gap: 20px;<?php if($block->dataValue('reverse')):?> flex-direction: row-reverse;<?php endif;?>">
      <div class="card-body card" style="border: 1px solid rgba(0,0,0,.125); border-radius: 0.25rem; flex: 1 1 fit-content;">
      <?php if($block->dataValue('title')):?>
        <h2 class="card-title"><?php echo $block->dataValue('title');?></h2>
      <?php endif;?> 
      <?php echo $block->dataValue('text');?>
      </div>
      <figure onclick="OpenImage('<?php echo $oUrl;?>')" class="openimage card" style="flex: 1 <?php echo $shrink;?> fit-content;">
        <img src="<?php echo $oUrl;?>" style="aspect-ratio: <?php echo $ratio;?>; display: block; max-width: 100%; height: 100%; object-fit: <?php echo $objectfit;?>;border-radius: 1%;">
        <?php if($attachments[0]->caption()):?>
        <figcaption class="figs"><?php echo $attachments[0]->caption();?></figcaption>
        <?php endif;?>
      </figure>
    </div>
  </div>
</section>
