<?php
$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$url = $this->plugin('url');
$this->htmlElement('body')->appendAttribute('class', 'index search');
?>
<section class="section">
  <div class="container">
    <h1 class="title is-2 is-family-secondary"><?php echo sprintf($this->translate('Search results for “%s”'), $query); ?></h1>
    
    <?php if (empty($results)): ?>
        <p><?php echo $translate('No result found'); ?></p>
    <?php else: ?>
      <?php
        $resourceLabels = [
            'site_pages' => 'Site pages', // @translate
            'items' => 'Items', // @translate
            'item_sets' => 'Item sets', // @translate
            'media' => 'Media', // @translate
        ];
        $resourceControllers = [
            'site_pages' => 'page',
            'items' => 'item',
            'item_sets' => 'item-set',
            'media' => 'media',
        ];
      ?>
      
      <?php foreach ($results as $resourceName => $result): ?>
        <?php if($resourceName == 'site_pages'):?>
        <div class="content row">
        <div class="<?php echo $resourceName; ?> results col-6">
            <h2><?php echo $translate($resourceLabels[$resourceName]); ?></h2>

                <?php $titleMethod = $resourceName === 'site_pages' ? 'title' : 'displayTitle'; ?>
            <div class="list-group list-group-flush">
                <?php foreach ($result['resources'] as $resource): ?>

                    <?php echo $resource->link($resource->$titleMethod(), '', ['class' => 'list-group-item list-group-item-action', 'style' => 'color: rgb(0, 64, 112)']) ?>

                <?php endforeach; ?>
                </div>
                <?php echo $hyperlink(
                    sprintf($translate('View all results (%s total)'), $result['total']),
                    $url(
                        'site/resource',
                        ['controller' => $resourceControllers[$resourceName], 'action' => 'browse'],
                        ['query' => ['fulltext_search' => $query]],
                        true
                    ),
                    ['class' => 'btn btn-ghost', 'style' => 'margin-top: 5px']
                ); ?>
        </div>
        </div>
        <?php endif;?>
      <?php endforeach; ?>
      <?php endif;?>
      
    </div>  
</section>